In [19]:
import pandas as pd

In [20]:
import numpy as np

In [6]:
 df = pd.read_csv("health_care (1).csv")

In [5]:

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [11]:
print(df.shape)

(768, 9)

In [13]:
print(df.columns)

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [21]:
numerical_features = df.select_dtypes(include=np.number).columns
categorical_features = df.select_dtypes(include=['object']).columns

In [23]:
print("Numerical Features:", numerical_features)
print("Categorical_features:",categorical_features)

Numerical Features: Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')
Categorical_features: Index([], dtype='object')

In [24]:
print("missing values:")

missing values:

In [26]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [28]:
for col in numerical_features:
    df[col].fillna(df[col].median(),inplace=True)

In [32]:
for col in categorical_features:
    df[col].fillna(df[col].mode()[0],inplace=True)

In [34]:
df.drop_duplicates(inplace=True)
print("Duplicates removed")

Duplicates removed

In [37]:
from sklearn.preprocessing import LabelEncoder

In [39]:
le = LabelEncoder()
for col in categorical_features:
    df[col] = le.fit_transform(df[col])

In [41]:
df = pd.get_dummies(df,columns=categorical_features)

In [45]:
q1 = df[numerical_features].quantile(0.25)
q2 = df[numerical_features].quantile(0.75)
iqr = q2 - q1

In [48]:
df = df[((df[numerical_features]< (q1 - 1.5 * iqr)))
]

In [66]:
(df[numerical_features] > (q2 + 1.5 * iqr)).any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [68]:
print("final dataset shape:",df.shape)
df.head()

final dataset shape: (768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN